create extension if not exists pgcrypto;

create table if not exists public.question_revisions (
  id uuid primary key default gen_random_uuid(),
  question_id uuid not null references public.questions(id) on delete cascade,
  revision_no integer not null check (revision_no > 0),
  display_question text,
  display_answer text,
  display_analysis text,
  correct_answer_override text check (correct_answer_override is null or correct_answer_override ~ '^[A-F]+$'),
  question_type_override text check (question_type_override is null or question_type_override in ('单选题', '多选题', '大题')),
  scoring_points jsonb not null default '[]'::jsonb check (jsonb_typeof(scoring_points) = 'array'),
  keywords jsonb not null default '[]'::jsonb check (jsonb_typeof(keywords) = 'array'),
  common_mistakes jsonb not null default '[]'::jsonb check (jsonb_typeof(common_mistakes) = 'array'),
  revision_note text not null,
  verification_reference text,
  created_at timestamptz not null default now(),
  unique (question_id, revision_no)
);

create table if not exists public.question_quality (
  question_id uuid primary key references public.questions(id) on delete cascade,
  publication_status text not null default 'published'
    check (publication_status in ('published', 'hidden_duplicate', 'hidden_error', 'hidden_review')),
  review_status text not null default 'unreviewed'
    check (review_status in ('unreviewed', 'structural_checked', 'source_verified', 'needs_manual_review')),
  canonical_question_id uuid references public.questions(id) on delete restrict,
  chapter_confidence numeric check (chapter_confidence is null or (chapter_confidence >= 0 and chapter_confidence <= 1)),
  verification_status text not null default 'pending'
    check (verification_status in ('teacher-key-verified', 'textbook-law-verified', 'authoritative-source-verified', 'source-backed', 'pending')),
  source_kind text,
  source_title text,
  source_edition text,
  source_chapter text,
  source_page text,
  source_url text,
  verification_reference text,
  current_revision_id uuid references public.question_revisions(id) on delete set null,
  original_payload_hash text not null check (original_payload_hash ~ '^[a-f0-9]{64}$'),
  verified_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (canonical_question_id is null or canonical_question_id <> question_id),
  check (publication_status <> 'hidden_duplicate' or canonical_question_id is not null)
);

create table if not exists public.question_quality_events (
  id bigint generated by default as identity primary key,
  question_id uuid not null references public.questions(id) on delete cascade,
  event_type text not null,
  before_state jsonb,
  after_state jsonb,
  actor text not null default current_user,
  created_at timestamptz not null default now()
);

create index if not exists question_quality_publication_idx
  on public.question_quality (publication_status, review_status);
create index if not exists question_quality_canonical_idx
  on public.question_quality (canonical_question_id)
  where canonical_question_id is not null;
create index if not exists question_revisions_question_idx
  on public.question_revisions (question_id, revision_no desc);
create index if not exists question_quality_events_question_idx
  on public.question_quality_events (question_id, created_at desc);

insert into public.question_quality (
  question_id,
  publication_status,
  review_status,
  verification_status,
  source_kind,
  source_title,
  verification_reference,
  original_payload_hash,
  verified_at
)
select
  q.id,
  'published',
  case
    when q.payload ->> 'auditStatus' in ('teacher-key-verified', 'textbook-law-verified', 'authoritative-source-verified')
      and nullif(trim(q.payload ->> 'verificationReference'), '') is not null then 'source_verified'
    when q.payload ->> 'auditStatus' = 'source-backed' then 'structural_checked'
    else 'needs_manual_review'
  end,
  case
    when q.payload ->> 'auditStatus' in ('teacher-key-verified', 'textbook-law-verified', 'authoritative-source-verified', 'source-backed')
      then q.payload ->> 'auditStatus'
    else 'pending'
  end,
  case
    when coalesce(q.payload ->> 'source', '') ~ '教师|老师|课堂' then 'teacher-material'
    when coalesce(q.payload ->> 'source', '') ~ '真题|考试大纲|自学考试' then 'public-exam'
    when coalesce(q.payload ->> 'source', '') ~ '教材|课程|整理' then 'textbook-review'
    else 'question-bank'
  end,
  nullif(trim(q.payload ->> 'source'), ''),
  nullif(trim(q.payload ->> 'verificationReference'), ''),
  encode(digest(q.payload::text, 'sha256'), 'hex'),
  case
    when q.payload ->> 'auditStatus' in ('teacher-key-verified', 'textbook-law-verified', 'authoritative-source-verified')
      and nullif(trim(q.payload ->> 'verificationReference'), '') is not null then now()
    else null
  end
from public.questions q
on conflict (question_id) do nothing;

create or replace function public.initialize_question_quality()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.question_quality (
    question_id,
    publication_status,
    review_status,
    verification_status,
    source_kind,
    source_title,
    verification_reference,
    original_payload_hash,
    verified_at
  ) values (
    new.id,
    'published',
    case
      when new.payload ->> 'auditStatus' in ('teacher-key-verified', 'textbook-law-verified', 'authoritative-source-verified')
        and nullif(trim(new.payload ->> 'verificationReference'), '') is not null then 'source_verified'
      when new.payload ->> 'auditStatus' = 'source-backed' then 'structural_checked'
      else 'needs_manual_review'
    end,
    case
      when new.payload ->> 'auditStatus' in ('teacher-key-verified', 'textbook-law-verified', 'authoritative-source-verified', 'source-backed')
        then new.payload ->> 'auditStatus'
      else 'pending'
    end,
    case
      when coalesce(new.payload ->> 'source', '') ~ '教师|老师|课堂' then 'teacher-material'
      when coalesce(new.payload ->> 'source', '') ~ '真题|考试大纲|自学考试' then 'public-exam'
      when coalesce(new.payload ->> 'source', '') ~ '教材|课程|整理' then 'textbook-review'
      else 'question-bank'
    end,
    nullif(trim(new.payload ->> 'source'), ''),
    nullif(trim(new.payload ->> 'verificationReference'), ''),
    encode(digest(new.payload::text, 'sha256'), 'hex'),
    case
      when new.payload ->> 'auditStatus' in ('teacher-key-verified', 'textbook-law-verified', 'authoritative-source-verified')
        and nullif(trim(new.payload ->> 'verificationReference'), '') is not null then now()
      else null
    end
  ) on conflict (question_id) do nothing;
  return new;
end;
$$;

drop trigger if exists questions_initialize_quality on public.questions;
create trigger questions_initialize_quality
after insert on public.questions
for each row execute function public.initialize_question_quality();

create or replace function public.prevent_question_payload_update()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.payload is distinct from old.payload then
    raise exception 'questions.payload is immutable; create a question revision instead';
  end if;
  return new;
end;
$$;

drop trigger if exists questions_prevent_payload_update on public.questions;
create trigger questions_prevent_payload_update
before update of payload on public.questions
for each row execute function public.prevent_question_payload_update();

create or replace function public.validate_question_quality_links()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  revision_question_id uuid;
begin
  if new.current_revision_id is not null then
    select question_id into revision_question_id
    from public.question_revisions
    where id = new.current_revision_id;
    if revision_question_id is null or revision_question_id <> new.question_id then
      raise exception 'current revision must belong to the same question';
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists question_quality_validate_links on public.question_quality;
create trigger question_quality_validate_links
before insert or update of current_revision_id on public.question_quality
for each row execute function public.validate_question_quality_links();

drop trigger if exists question_quality_set_updated_at on public.question_quality;
create trigger question_quality_set_updated_at
before update on public.question_quality
for each row execute function public.set_updated_at();

create or replace function public.log_question_quality_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.question_quality_events (question_id, event_type, before_state, after_state)
  values (new.question_id, 'quality-update', to_jsonb(old), to_jsonb(new));
  return new;
end;
$$;

drop trigger if exists question_quality_log_change on public.question_quality;
create trigger question_quality_log_change
after update on public.question_quality
for each row execute function public.log_question_quality_change();

create or replace function public.is_question_published(target_question_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.question_quality
    where question_id = target_question_id
      and publication_status = 'published'
  );
$$;

create or replace function public.is_current_published_revision(target_revision_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.question_quality
    where current_revision_id = target_revision_id
      and publication_status = 'published'
  );
$$;

revoke all on function public.is_question_published(uuid) from public;
revoke all on function public.is_current_published_revision(uuid) from public;
grant execute on function public.is_question_published(uuid) to authenticated;
grant execute on function public.is_current_published_revision(uuid) to authenticated;

alter table public.question_quality enable row level security;
alter table public.question_revisions enable row level security;
alter table public.question_quality_events enable row level security;

drop policy if exists "active members can read questions" on public.questions;
create policy "active members can read published questions"
on public.questions
for select
to authenticated
using (public.is_active_member() and public.is_question_published(id));

drop policy if exists "active members can read published question quality" on public.question_quality;
create policy "active members can read published question quality"
on public.question_quality
for select
to authenticated
using (public.is_active_member() and publication_status = 'published');

drop policy if exists "active members can read current question revisions" on public.question_revisions;
create policy "active members can read current question revisions"
on public.question_revisions
for select
to authenticated
using (public.is_active_member() and public.is_current_published_revision(id));

revoke all on table public.question_quality from anon, authenticated;
revoke all on table public.question_revisions from anon, authenticated;
revoke all on table public.question_quality_events from anon, authenticated;
grant select on table public.question_quality to authenticated;
grant select on table public.question_revisions to authenticated;
grant all on table public.question_quality to service_role;
grant all on table public.question_revisions to service_role;
grant all on table public.question_quality_events to service_role;

comment on table public.question_quality is
  'Non-destructive publication, review, source, canonical and current-revision metadata for questions.';
comment on table public.question_revisions is
  'Display overrides and editorial scoring metadata; original questions.payload remains immutable.';
comment on table public.question_quality_events is
  'Append-only audit history for question quality state changes.';
